#!/bin/sh

# Remove shutdown and reboot links; this init script does not need them.
if dpkg --compare-versions "$2" lt "1.1.12-1ubuntu1"; then
	rm -f /etc/rc0.d/K20keepalived /etc/rc6.d/K20keepalived
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/keepalived" ]; then
	update-rc.d keepalived defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d keepalived start || exit $?
	else
		/etc/init.d/keepalived start || exit $?
	fi
fi
# End automatically added section

